summary(iris)
head(iris)
by(iris$Petal.Length, iris$Species, summary)
mean(iris$Sepal.Length)
var(iris$Sepal.Length)
boxplot(iris$Petal.Length)
boxplot(Petal.Length~Species, data = iris, main = "Petal Length", xlab = "Species", ylab = "Length")

hist(iris$Petal.Length)
hist(iris$Sepal.Width)
hist(iris$Sepal.Width[iris$Species=="setosa"])
hist(iris$Sepal.Width[iris$Species=="versicolor"])
d=density(iris$Petal.Length)
plot(d)
d=density(iris$Sepal.Width[iris$Species=="versicolor"])
plot(d)

library(ggplot2)
data_houseprices <- read.csv("C:/probstat/houseprice.csv", sep = ",")
qplot(data_rafael$AmountSpent, data_rafael$Salary)
plot(data_rafael$AmountSpent, data_rafael$Salary)
hist(data_rafael$AmountSpent)
d=density(data_rafael$AmountSpent)
plot(d)

data_rafaelgala = read.csv("clipboard", sep = ",")
plot(data_rafaelgala$Price, data_calistaazzahra$SqFt, xlab = "SqFt", ylab = "price")